
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core sdk'
  inputs:
    packageType: 'sdk'
    version: 2.1.x
    performMultiLevelLookup: true
    
    
- task: UseDotNet@2
  inputs:
    version: 2.1.x
  displayName: setdotnet version to use

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfigurations)'
- task: DotNetCoreCLI@2
  displayName: binaries
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
    
- task: PublishBuildArtifacts@1
  displayName: publish
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Drop'

